# Base spec
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-update
spec:
  params:
    - description: url of the git repo for the code of deployment
      name: git-url
      type: string
    - default: main
      description: revision to be used from repo of the code for deployment
      name: git-revision
      type: string
    - description: image to be build from the code
      name: new-image
      type: string
  # tasks that will run
  tasks:
    # fetches code. set sslVerify to false if no trusted cert
    - name: fetch-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.git-revision)
        - name: sslVerify
          value: 'false'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    # build the image.
    - name: build-image
      params:
        - name: IMAGE
          value: $(params.new-image)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    # kustomize.

