apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: clone-build-update-trigger
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "gitlab"
      params:
        - name: "secretRef"
          value:
            secretName: gitlab-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["Push Hook"]
  bindings:
    - ref: hello-openshift-tb
  template:
    ref: clone-build-update-tt
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
type: Opaque
stringData:
  secretToken: "1234567"